# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/bartesaghia/code/cmake-2.8.2-Linux-i386/bin/cmake

# The command to remove a file.
RM = /home/bartesaghia/code/cmake-2.8.2-Linux-i386/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /home/bartesaghia/code/cmake-2.8.2-Linux-i386/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bartesaghia/scripts/SPA/CSP/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bartesaghia/scripts/SPA/CSP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/bartesaghia/code/cmake-2.8.2-Linux-i386/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/bartesaghia/code/cmake-2.8.2-Linux-i386/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bartesaghia/scripts/SPA/CSP/CMakeFiles /home/bartesaghia/scripts/SPA/CSP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bartesaghia/scripts/SPA/CSP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SPA_euler_angles

# Build rule for target.
SPA_euler_angles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SPA_euler_angles
.PHONY : SPA_euler_angles

# fast build rule for target.
SPA_euler_angles/fast:
	$(MAKE) -f CMakeFiles/SPA_euler_angles.dir/build.make CMakeFiles/SPA_euler_angles.dir/build
.PHONY : SPA_euler_angles/fast

#=============================================================================
# Target rules for targets named SPA_statistics

# Build rule for target.
SPA_statistics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SPA_statistics
.PHONY : SPA_statistics

# fast build rule for target.
SPA_statistics/fast:
	$(MAKE) -f CMakeFiles/SPA_statistics.dir/build.make CMakeFiles/SPA_statistics.dir/build
.PHONY : SPA_statistics/fast

#=============================================================================
# Target rules for targets named csp

# Build rule for target.
csp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csp
.PHONY : csp

# fast build rule for target.
csp/fast:
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/build
.PHONY : csp/fast

#=============================================================================
# Target rules for targets named gaussian_distribution

# Build rule for target.
gaussian_distribution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gaussian_distribution
.PHONY : gaussian_distribution

# fast build rule for target.
gaussian_distribution/fast:
	$(MAKE) -f CMakeFiles/gaussian_distribution.dir/build.make CMakeFiles/gaussian_distribution.dir/build
.PHONY : gaussian_distribution/fast

SPA_euler_angles.o: SPA_euler_angles.cpp.o
.PHONY : SPA_euler_angles.o

# target to build an object file
SPA_euler_angles.cpp.o:
	$(MAKE) -f CMakeFiles/SPA_euler_angles.dir/build.make CMakeFiles/SPA_euler_angles.dir/SPA_euler_angles.cpp.o
.PHONY : SPA_euler_angles.cpp.o

SPA_euler_angles.i: SPA_euler_angles.cpp.i
.PHONY : SPA_euler_angles.i

# target to preprocess a source file
SPA_euler_angles.cpp.i:
	$(MAKE) -f CMakeFiles/SPA_euler_angles.dir/build.make CMakeFiles/SPA_euler_angles.dir/SPA_euler_angles.cpp.i
.PHONY : SPA_euler_angles.cpp.i

SPA_euler_angles.s: SPA_euler_angles.cpp.s
.PHONY : SPA_euler_angles.s

# target to generate assembly for a file
SPA_euler_angles.cpp.s:
	$(MAKE) -f CMakeFiles/SPA_euler_angles.dir/build.make CMakeFiles/SPA_euler_angles.dir/SPA_euler_angles.cpp.s
.PHONY : SPA_euler_angles.cpp.s

SPA_statistics.o: SPA_statistics.cpp.o
.PHONY : SPA_statistics.o

# target to build an object file
SPA_statistics.cpp.o:
	$(MAKE) -f CMakeFiles/SPA_statistics.dir/build.make CMakeFiles/SPA_statistics.dir/SPA_statistics.cpp.o
.PHONY : SPA_statistics.cpp.o

SPA_statistics.i: SPA_statistics.cpp.i
.PHONY : SPA_statistics.i

# target to preprocess a source file
SPA_statistics.cpp.i:
	$(MAKE) -f CMakeFiles/SPA_statistics.dir/build.make CMakeFiles/SPA_statistics.dir/SPA_statistics.cpp.i
.PHONY : SPA_statistics.cpp.i

SPA_statistics.s: SPA_statistics.cpp.s
.PHONY : SPA_statistics.s

# target to generate assembly for a file
SPA_statistics.cpp.s:
	$(MAKE) -f CMakeFiles/SPA_statistics.dir/build.make CMakeFiles/SPA_statistics.dir/SPA_statistics.cpp.s
.PHONY : SPA_statistics.cpp.s

flrClasses.o: flrClasses.cxx.o
.PHONY : flrClasses.o

# target to build an object file
flrClasses.cxx.o:
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/flrClasses.cxx.o
.PHONY : flrClasses.cxx.o

flrClasses.i: flrClasses.cxx.i
.PHONY : flrClasses.i

# target to preprocess a source file
flrClasses.cxx.i:
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/flrClasses.cxx.i
.PHONY : flrClasses.cxx.i

flrClasses.s: flrClasses.cxx.s
.PHONY : flrClasses.s

# target to generate assembly for a file
flrClasses.cxx.s:
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/flrClasses.cxx.s
.PHONY : flrClasses.cxx.s

flrCostFunctions.o: flrCostFunctions.cxx.o
.PHONY : flrCostFunctions.o

# target to build an object file
flrCostFunctions.cxx.o:
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/flrCostFunctions.cxx.o
.PHONY : flrCostFunctions.cxx.o

flrCostFunctions.i: flrCostFunctions.cxx.i
.PHONY : flrCostFunctions.i

# target to preprocess a source file
flrCostFunctions.cxx.i:
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/flrCostFunctions.cxx.i
.PHONY : flrCostFunctions.cxx.i

flrCostFunctions.s: flrCostFunctions.cxx.s
.PHONY : flrCostFunctions.s

# target to generate assembly for a file
flrCostFunctions.cxx.s:
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/flrCostFunctions.cxx.s
.PHONY : flrCostFunctions.cxx.s

flrMain.o: flrMain.cxx.o
.PHONY : flrMain.o

# target to build an object file
flrMain.cxx.o:
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/flrMain.cxx.o
.PHONY : flrMain.cxx.o

flrMain.i: flrMain.cxx.i
.PHONY : flrMain.i

# target to preprocess a source file
flrMain.cxx.i:
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/flrMain.cxx.i
.PHONY : flrMain.cxx.i

flrMain.s: flrMain.cxx.s
.PHONY : flrMain.s

# target to generate assembly for a file
flrMain.cxx.s:
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/flrMain.cxx.s
.PHONY : flrMain.cxx.s

flrReadParametersFile.o: flrReadParametersFile.cxx.o
.PHONY : flrReadParametersFile.o

# target to build an object file
flrReadParametersFile.cxx.o:
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/flrReadParametersFile.cxx.o
.PHONY : flrReadParametersFile.cxx.o

flrReadParametersFile.i: flrReadParametersFile.cxx.i
.PHONY : flrReadParametersFile.i

# target to preprocess a source file
flrReadParametersFile.cxx.i:
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/flrReadParametersFile.cxx.i
.PHONY : flrReadParametersFile.cxx.i

flrReadParametersFile.s: flrReadParametersFile.cxx.s
.PHONY : flrReadParametersFile.s

# target to generate assembly for a file
flrReadParametersFile.cxx.s:
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/flrReadParametersFile.cxx.s
.PHONY : flrReadParametersFile.cxx.s

flrSPAEulerAngles.o: flrSPAEulerAngles.cxx.o
.PHONY : flrSPAEulerAngles.o

# target to build an object file
flrSPAEulerAngles.cxx.o:
	$(MAKE) -f CMakeFiles/SPA_euler_angles.dir/build.make CMakeFiles/SPA_euler_angles.dir/flrSPAEulerAngles.cxx.o
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/flrSPAEulerAngles.cxx.o
.PHONY : flrSPAEulerAngles.cxx.o

flrSPAEulerAngles.i: flrSPAEulerAngles.cxx.i
.PHONY : flrSPAEulerAngles.i

# target to preprocess a source file
flrSPAEulerAngles.cxx.i:
	$(MAKE) -f CMakeFiles/SPA_euler_angles.dir/build.make CMakeFiles/SPA_euler_angles.dir/flrSPAEulerAngles.cxx.i
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/flrSPAEulerAngles.cxx.i
.PHONY : flrSPAEulerAngles.cxx.i

flrSPAEulerAngles.s: flrSPAEulerAngles.cxx.s
.PHONY : flrSPAEulerAngles.s

# target to generate assembly for a file
flrSPAEulerAngles.cxx.s:
	$(MAKE) -f CMakeFiles/SPA_euler_angles.dir/build.make CMakeFiles/SPA_euler_angles.dir/flrSPAEulerAngles.cxx.s
	$(MAKE) -f CMakeFiles/csp.dir/build.make CMakeFiles/csp.dir/flrSPAEulerAngles.cxx.s
.PHONY : flrSPAEulerAngles.cxx.s

gaussian_distribution.o: gaussian_distribution.cpp.o
.PHONY : gaussian_distribution.o

# target to build an object file
gaussian_distribution.cpp.o:
	$(MAKE) -f CMakeFiles/gaussian_distribution.dir/build.make CMakeFiles/gaussian_distribution.dir/gaussian_distribution.cpp.o
.PHONY : gaussian_distribution.cpp.o

gaussian_distribution.i: gaussian_distribution.cpp.i
.PHONY : gaussian_distribution.i

# target to preprocess a source file
gaussian_distribution.cpp.i:
	$(MAKE) -f CMakeFiles/gaussian_distribution.dir/build.make CMakeFiles/gaussian_distribution.dir/gaussian_distribution.cpp.i
.PHONY : gaussian_distribution.cpp.i

gaussian_distribution.s: gaussian_distribution.cpp.s
.PHONY : gaussian_distribution.s

# target to generate assembly for a file
gaussian_distribution.cpp.s:
	$(MAKE) -f CMakeFiles/gaussian_distribution.dir/build.make CMakeFiles/gaussian_distribution.dir/gaussian_distribution.cpp.s
.PHONY : gaussian_distribution.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... SPA_euler_angles"
	@echo "... SPA_statistics"
	@echo "... csp"
	@echo "... edit_cache"
	@echo "... gaussian_distribution"
	@echo "... rebuild_cache"
	@echo "... SPA_euler_angles.o"
	@echo "... SPA_euler_angles.i"
	@echo "... SPA_euler_angles.s"
	@echo "... SPA_statistics.o"
	@echo "... SPA_statistics.i"
	@echo "... SPA_statistics.s"
	@echo "... flrClasses.o"
	@echo "... flrClasses.i"
	@echo "... flrClasses.s"
	@echo "... flrCostFunctions.o"
	@echo "... flrCostFunctions.i"
	@echo "... flrCostFunctions.s"
	@echo "... flrMain.o"
	@echo "... flrMain.i"
	@echo "... flrMain.s"
	@echo "... flrReadParametersFile.o"
	@echo "... flrReadParametersFile.i"
	@echo "... flrReadParametersFile.s"
	@echo "... flrSPAEulerAngles.o"
	@echo "... flrSPAEulerAngles.i"
	@echo "... flrSPAEulerAngles.s"
	@echo "... gaussian_distribution.o"
	@echo "... gaussian_distribution.i"
	@echo "... gaussian_distribution.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

