#!/bin/bash
#
#   Script for running FREALIGN refinement on Biowulf using SWARM.
#   FREALIGN paremeters must be specified in "mparameters" file.
#       This file should be present in the working directory.
#   Working directory structure:
#       /scratch - intermediate output generated by FREALIGN.
#       /maps    - alignment and maps for each refinement iteration.
#   A typical usage sequence would be:
#               cd $project/swarm
#       frealign_ali.sh 2; frealign_rec.sh 2;
#       frealign_ali.sh 3; frealign_rec.sh 3;
#               etc.
# 
# $Id: frealign_ali.sh 142 2009-12-16 03:38:21Z fefo $

# Test whether command-line argument is present (non-empty).
if ! [ -n "$2" ]; then
    echo "Usage: `basename $0` iteration_number data_input"
    exit 1
else
	echo "[`date '+%Y%m%d-%H%M%S'`] `basename $0` $@"
fi  

iter=$1
dataset=$2

let prev=$iter-1

cd scratch

reference=../maps/${dataset}_CSP_`printf %02d ${prev}`.mrc
image_stack=../${dataset}_stack.mrc
inDotPar=${dataset}_CSP_`printf %02d ${iter}`.parx
com="${CSPDIR}/frealign/msearch_n.sh ${dataset}_CSP ${image_stack} ${iter} ${reference} ${inDotPar}"
echo $com
$com

cd - > /dev/null
